setup.py
Versioning requires 4.0, but it's not released yet. tox installs correct version anyway.
=> Revert dependency on CMS version

djangocms_versioning/admin.py, tests/test_admin.py
This PR includes enabling admin views (publish, unpublish, archive, edit_redirect) only accept POST method.
=> Enabling POST only for required admin views

djangocms_versioning/admin.py, djangocms_versioning/constants.py, djangocms_versioning/helpers.py, tests/test_version_list.py
There are two functions available, `version_list_url` should be preferred, unless content object is unavailable (example: https://github.com/divio/djangocms-alias/blob/214a08a3f76192f8dace7a02c797ecba90d9f3c7/djangocms_alias/models.py#L134). `version_list_url` will be extended to language-awareness later on.
=> Add public functions for retrieving version list URLs

djangocms_versioning/test_utils/test_helpers.py, tests/test_toolbars.py
This saves having to change every app when minor changes are made to the core CMS project.
Moderation and Version locking will reuse the test helpers, if in future the helper needs to diverge any of the projects can copy their own version. The idea is for now to standardise the tests and to help save time debugging as a lot of time has been spent debugging the different versions of this one helper that is repeated in all three projects.
=> Create a toolbar test helper for other apps to reuse. 

djangocms_versioning/migrations/0012_create_version_numbers.py
Remove 0012 data migration script because versions will always be created after this point, and it is causing dependency problems with other packages tests. Anyone that requires this migration can install version 0.0.23, which is the last version with it enabled.
=> comment out 0012 data migration forward logic

djangocms_versioning/admin.py, setup.py, tests/test_admin.py
When a versioned model with additional grouping values is selected in the Admin the following error is thrown:
```
DoesNotExist at /admin/djangocms_versioning/menucontentversion/
MenuContentVersion matching query does not exist.
http://127.0.0.1:8000/admin/djangocms_versioning/menucontentversion/?language=ja&menu=29
/usr/local/lib/python3.6/site-packages/djangocms_versioning/admin.py in changelist_view
Line 846 .latest("created") 
```
The error is thrown because the language filtered is empty.
Steps to replicate:
1. Create a page with multiple languages
2. Add content to one of the languages
3. Go to the admin changelist
4. Select the filter for the language that has no content
5. Bosh, error thrown.
Images showing the error before the fix in this PR: 
Images showing no error with the …
=> Fix admin change list empty translation / additional grouping values query error

djangocms_versioning/cms_config.py, djangocms_versioning/monkeypatch/page.py, djangocms_versioning/test_utils/factories.py, tests/test_cms_config.py
The urls does not need to be updated at all. The reason urls
were presumably updated in the past was to avoid that you could
visit a page if the page was in draft mode.
This has been fixed in django-cms. A page that is in draft
will return an EmptyPageContent, if it is empty it won't render.
See divio/django-cms#6803
Added tests are mostly for documentation purposes to see expected behaviour. 
From @jonathan-s 11th Feb 2020 justifying why we need to make this change:
On the off chance that there is a page that uses the old structure and there is a change that requires it I've left it in. 
So the scenario is the following. User creates a page, pagecontent is in draft. User publishes pagecontent. They change the path to something custom (this sets managed to False in that url). Prior to …
=> Urls no longer need to be updated

djangocms_versioning/helpers.py, tests/test_models.py
If an another package for whatever reason needs to return the whole queryset and can't use the original manager. The following helper method filters out the `where = 'published'` statement that the versioning package adds to the queryset by default for any version.
=> Add helper method to return all queries

.circleci/config.yml, README.rst, djangocms_versioning/monkeypatch/toolbar.py, setup.py, tests/requirements.txt, tox.ini
Currently it's failing so this a WIP investigation to figure out why. 
TypeError: Cannot use cached_property instance without calling `__set_name__()` on it.
when `__set_name__` is being called on the cached property, the cached property function is being replaced by the real function. 
When `__set_name__` is not called, this replacement does not happen, which executes the cached property function which subsequently throws an error. 
So for some reason cached property's `__set_name__` is not being called even though it should be. 
Django had a similar bug where this happened: 
- https://github.com/django/django/pull/10763/files
- https://code.djangoproject.com/ticket/29970
This is the error that is being thrown for `cached_property` …
=> Support django2.2

djangocms_versioning/monkeypatch/admin.py, tests/test_monkeypatch.py
`RequestToolbarForm` in django-cms needs to be able to fetch objects that are in draft as well. A method `get_admin_model_object_by_id` was created in the following PR (https://github.com/divio/django-cms/pull/6806) to allow versioning to monkeypatch this method.
=> Monkeypatch so that draft object can be retrieved

djangocms_versioning/admin.py, tests/test_toolbars.py
In Django 2.2 a JS load error has started to occur in the Versioning admin. It's possibly due to the change of how Django now sorts Media assets: https://docs.djangoproject.com/en/3.0/releases/2.2/#merging-of-form-media-assets
A screenshot of the issue occurring, without the fix in this PR:
A screenshot of the issue no longer occurring with the fix in this PR:
=> Fixed a JS load error inherited by all Admins from versioning

djangocms_versioning/models.py, djangocms_versioning/test_utils/factories.py, tests/requirements.txt
DB's are left in a corrupt state if the copy function is partially successful where Page, PageContent, Placeholder, Plugin models are created when a plugin copy error occurs.
The copy method should always run in a transaction to be sure that there is always a content object with a version!
=> Fix copy method not creating a version for the content model on error

djangocms_versioning/test_utils/factories.py, tests/requirements.txt
The djangocms-text-ckeditor package has been recently updated for cms3 to 4.0.x, we need to support the django-cms release 4.0.x branch not the djangocms-text-ckeditor 4.0.x release.
=> Pin the djangocms-text-ckeditor package to the v4 branch for the test suite

djangocms_versioning/admin.py, djangocms_versioning/templates/djangocms_versioning/admin/compare.html, tests/test_admin.py
Changes added to display Content version number instead verion pk in compare view and also updated local timezone date display in compare
Current
Updated
=> Changes added to display Content version number along with pk in compare view

djangocms_versioning/cms_config.py, djangocms_versioning/monkeypatch/extensions.py, djangocms_versioning/test_utils/extended_polls/admin.py, djangocms_versioning/test_utils/extended_polls/models.py, djangocms_versioning/test_utils/extended_polls/templates/extended_polls/extended_polls.html, djangocms_versioning/test_utils/factories.py, setup.py, test_settings.py, tests/requirements.txt, tests/test_admin.py, tests/test_handlers.py, tests/test_models.py, tests/test_monkeypatch.py, tests/test_states.py
Copy method added to allow versioning, as well as monkey patch to override versioning query set filters when saving and adding extensions.
=> Feature: Copy method and Monkeypatch CMS Pagecontent Admin Extensions

CHANGELOG.rst, djangocms_versioning/admin.py, tests/requirements/requirements_base.txt
Field ordering was missing in the generic admin mixing for state, author and modified date. This PR adds those.
=> Fix: Field Ordering Added to Generic Versioning Mixin

CHANGELOG.rst, djangocms_versioning/__init__.py
* fix: Page Content Extended models do no update the version modified date as they should.
=> Release 0.0.33

CHANGELOG.rst, djangocms_versioning/__init__.py
* Python 3.8, 3.9 support added
* Django 3.0, 3.1 and 3.2 support added
* Python 3.5 and 3.6 support removed
* Django 1.11 support removed
=> Release 1.0.0

CHANGELOG.rst, djangocms_versioning/admin.py, djangocms_versioning/datastructures.py, djangocms_versioning/templates/djangocms_versioning/admin/edit_icon.html, tests/test_admin.py, tests/test_datastructures.py
An issue is present where all items in the Version Changelist table are opened outside of the sideframe when the edit icon is clicked. This should only be the case for PageContents and any other items with Placeholders that require a dedicated edit endpoint with a toolbar. All other items should continue to open in the sideframe. 
Due to the nature of the check, the caching (cached property) prevents the calculation happening for every table row when rendering the Changelist, it is done once per model with VersioningItem configuration. 
=> fix: The version changelist table edit button opens all items outside of the sideframe

CHANGELOG.rst, djangocms_versioning/__init__.py
* fix: Version Changelist table edit button opens all items out of the sideframe
=> Release 1.0.6

CHANGELOG.rst, djangocms_versioning/__init__.py, djangocms_versioning/cms_toolbars.py, djangocms_versioning/test_utils/test_helpers.py, tests/test_toolbars.py
Added a new button to the toolbar for pages that allows a user to navigate to the live url with ease.
* Initial implementation taken from: https://github.com/django-cms/djangocms-versioning/pull/281
=> feat: Add a 'View Published' button for page edit or preview mode

CHANGELOG.rst, djangocms_versioning/static/djangocms_versioning/js/actions.js
The admin burger menu does not work for any other language than English. This is an issue where the Preview and Edit buttons are added to the burger menu and any bound js events are stripped because a new dom element is created. 
=> fix: Admin burger menu excluding Preview and Edit buttons in all languages

.github/workflows/lint.yml, .github/workflows/test.yml, CHANGELOG.rst
Adds concurrency option to workflows.
What this does is if new changes are pushed and workflows are running, they'll be cancelled because the code they're checking is then out of date so the results are no longer relevant.
=> ci: Added concurrency to workflows

.github/workflows/test.yml, CHANGELOG.rst
Unused matrix option removed because the workflow always runs on latest ubuntu.
Checks marked as "Expected — Waiting for status to be reported" won't return a response because they're not going to run.
That's GH adding the OS from the matrix to the check name even though we never ran checks against the OS matrix values. I'll need to update the required checks once this is cleaned up.
=> ci: Remove ``os`` from test workflow matrix

.github/workflows/lint.yml, .github/workflows/test.yml, CHANGELOG.rst, test_settings.py
Most actions are now at version 3 so this moves them on. Coverage is at version 2.
=> ci: Update actions to latest versions

.github/workflows/lint.yml, CHANGELOG.rst
This updates the isort params for version 5.
https://pycqa.github.io/isort/docs/upgrade_guides/5.0.0.html
=> ci: Update isort params for v5

tests/requirements/requirements_base.txt
After merging #300 the test requirements need to be fixed against the `django-cms/develop-4` branch (which now also contains the changes needed for #300)
Additionally we can now use the latest released djangocms-text-ckeditor since as of 5.1.2 it supports django CMS 4
* #300
* #...
=> fix: test requirements after removing the patching pattern

djangocms_versioning/constants.py, djangocms_versioning/locale/de/LC_MESSAGES/django.po, djangocms_versioning/locale/en/LC_MESSAGES/django.po, djangocms_versioning/locale/fr/LC_MESSAGES/django.po, djangocms_versioning/locale/nl/LC_MESSAGES/django.po, djangocms_versioning/locale/sq/LC_MESSAGES/django.po, djangocms_versioning/models.py
constants.py = 4 fixed strings which dit not parsed through _()
models.py = 2 date fields which did not had verbose_name
=> Some fixed strings are now translatable

djangocms_versioning/cms_toolbars.py
Currently, there is no way to use the toolbar to get from viewing a published version of a page (or other object) back to its preview. The only option available is "Edit" which will create a new draft or go to an existing draft.
With this PR the view published mode will have an additional button to get (back) to the preview.
I expect it to create more transparency on the modes available with djangocms-verisoning
* Edit mode (as with the core): Visible to staff only
* Preview mode (incldeing draft content): Visible to staff only
* Published mode (only published content): Visible to the outside
Also there are use cases where published versions and the preview of a public version need to be compared:
* The **published version only contains public versioned items** 
* The **preview of a …
=> feat: Add preview button to view published mode

djangocms_versioning/managers.py, tests/test_extensions.py
The `admin_manager` of a versioned model provided access to `current_content_iterator` which allowed to "filter" out all current versions of the model: Either draft or published (if there is no draft). This API had the drawback that the result was not a queryset but an iterator (since the grouping was done in python).
This method is now replaced by `current_content()` which is a filter that returns a queryset that only contains the current verison of the objects. Not only is it more convenient to have a qs returned, the number of database hits reduces from O(n) with n being the number of objects to 1.
`current_content_iterator` is kept to ensure compatibility with django CMS v4.1.0rc1
* #...
* #...
[Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to …
=> feat: Huge performance improvement for admin_manager

CHANGELOG.rst, djangocms_versioning/admin.py, djangocms_versioning/indicators.py, djangocms_versioning/static/djangocms_versioning/css/actions.css, djangocms_versioning/static/djangocms_versioning/js/actions.js, djangocms_versioning/static/djangocms_versioning/js/indicators.js, tests/test_indicators.py
This PR fixes the burger menu to 
1. work with icons provided by the core
2. variable width content
3. Only display if there are elements in the burger menu
4. CMS style (same as e.g., state indicator drop down or page tree dropdowns)
=> fix: burger menu to also work with new core icons

CHANGELOG.rst, djangocms_versioning/cms_config.py, djangocms_versioning/test_utils/factories.py, tests/test_cms_config.py
Add a cache to `PageContent.__bool__`. I've experienced that on a typical CMS edit page there are thousands of calls to this function which all result in a database query.
Obviously this cache could become stale. If you have ideas where that could happen, please share. However, reducing a page load by 2000+ SQL queries sure seems like worth a try.
=> Add caching to PageContent __bool__

djangocms_versioning/helpers.py, djangocms_versioning/templates/djangocms_versioning/admin/discard_confirmation.html, djangocms_versioning/templates/djangocms_versioning/admin/revert_confirmation.html, djangocms_versioning/templates/djangocms_versioning/admin/unpublish_confirmation.html, tests/test_models.py
This PR adds the `.submit-row` `<div>` used in Django admin for more consistent styling.
It also removes an unused left-over helper function (legacy of pre-2.0):
* `djangocms_verisoning.helpers.remove_published_where(qs)` used to patch a queryset removing the resulting SQL `WHERE` statement which restricts the queryset to include published versions only.
* It is not used in the codebase any more. Usage in djangocms-alias has been removed a while ago.
* The official pattern is to use the `admin_manager` of a versioned model which as the name indicates should only be used in the admin.
* #...
* #...
=> fix: Update templates for better styling w/o djangocms-admin-style

djangocms_versioning/cms_config.py, tests/test_cms_config.py, tests/test_extensions.py
This PR fixes #342 and is based on #343. 
CMS extensions have a [`copy` method](https://github.com/django-cms/django-cms/blob/003104acefed079fc92a0689683fa34cfd01c94f/cms/extensions/models.py#L42-L56). It also takes care of calling `copy_relations`.  
djangocms-versioning needs not recreate this method where it can miss the call of `copy_relations` but instead can use the original method instead.
* #343 
* #342 
=> fix: PageContent extension's `copy_relations` method not called

.github/workflows/test.yml, djangocms_versioning/admin.py, djangocms_versioning/cms_config.py, djangocms_versioning/cms_menus.py, djangocms_versioning/cms_toolbars.py, djangocms_versioning/helpers.py, djangocms_versioning/indicators.py, djangocms_versioning/locale/de/LC_MESSAGES/django.po, djangocms_versioning/locale/en/LC_MESSAGES/django.po, djangocms_versioning/locale/fr/LC_MESSAGES/django.po, djangocms_versioning/locale/nl/LC_MESSAGES/django.po, djangocms_versioning/locale/sq/LC_MESSAGES/django.po, tests/requirements/requirements_base.txt, tests/test_admin.py, tests/test_locking.py, tox.ini
This PR fixes an issue with the preview links falling back to the primary language.
* No more jumping between languages when clicking preview in the version admin
* Comparing pages not of the primary language works
* #...
* #...
=> fix: Preview link language

.pre-commit-config.yaml, pyproject.toml
After checking ruff I made those update in order to solve warnings:
* updated the pyproject.toml file according to the documentation 
* updated repo of [pre-commit hook ](https://github.com/astral-sh/ruff-pre-commit)
* [ruff configuration](https://docs.astral.sh/ruff/tutorial/#configuration)
* [ruff-pre-commit](https://github.com/astral-sh/ruff-pre-commit)
=> Chore: update ruff and pre-commit hook

CHANGELOG.rst, djangocms_versioning/admin.py, djangocms_versioning/models.py, docs/signals.rst, tests/test_signals.py
Below two PRs should be compatible with djangocms 4.0.1.x version, so I cherry-pick them and merge into ``support/django-cms-4.0.x`` branch.
* feat: Provide additional information when sending publish/unpublish events (cherry-pick #348)
* fix:  Add keyword arguments in VersionAdminMixin render_change_form (cherry-pick #356)
=> Feat: merge missing publish updates

.github/workflows/lint.yml, djangocms_versioning/admin.py, tests/test_admin.py, tests/test_extensions.py, tests/test_handlers.py, tests/test_locking.py, tests/test_toolbars.py
Fixes #404 , where the edit action is shown for an unpublished version.
* #404 
* #...
=> fix: Do not show edit action for version objects where editing is not possible

djangocms_versioning/admin.py, djangocms_versioning/cms_config.py, djangocms_versioning/cms_toolbars.py, djangocms_versioning/helpers.py, djangocms_versioning/static/djangocms_versioning/css/object-tools.css, djangocms_versioning/static/djangocms_versioning/js/object-tools.js, djangocms_versioning/templates/admin/djangocms_versioning/page/change_form.html, djangocms_versioning/templates/admin/djangocms_versioning/versioning_buttons.html, djangocms_versioning/templates/djangocms_versioning/admin/mixin/change_form.html, djangocms_versioning/templatetags/djangocms_versioning.py, tests/test_admin.py
This PR adds standard versioning actions to the change of view of versioned objects, including page contents:
This includes a "New Draft" button for published versions:
Further improvements:
* "Versions" button takes the user to the version list.
* The version list includes a new settings action for frontend-editable versioned objects to be able to see the settings historic objects (such as meta tags for unpublished versions)
(For not frontend-editable objects, the "View" button already takes the user to the change view and no settings button is offered.)
Finally, this PR fixes a bug that prevented users from editing slugs in some cases. (https://github.com/django-cms/django-cms/issues/7866)
* https://github.com/django-cms/django-cms/issues/7909
* …
=> feat: Add versioning actions to settings (admin change view) of versioned objects

djangocms_versioning/plugin_rendering.py
Once, https://github.com/django-cms/django-cms/pull/7924 is merged, the work-around for page-specific rendering is not needed any more. This reactivates the `{% placeholder "my_placeholder" inherit %}` functionality.
Fixes #410.
Requires tests to be added.
* https://github.com/django-cms/django-cms/pull/7924
* #410 
=> fix: Remove workaround for page-specific rendering

djangocms_versioning/cms_toolbars.py
"Compare versions" offers a back button. This typically returns to the edit or preview endpoint. 
When editing a plugin and immediately afterwards clicking "Compare versions..." left the back button returning to an internal URL which only updates the toolbar.
This PR ensures that the correct toolbar request path is kept for the back button.
* #...
* #...
=> fix: Compare versions' back button sometimes returns to invalid URL

djangocms_versioning/cms_toolbars.py, djangocms_versioning/helpers.py, djangocms_versioning/indicators.py, tests/test_indicators.py
This PR halves the number of queries needed for the page tree's state indicator. This improves responsiveness of the page tree.
It also reduces the number of DB queries when populating the toolbar.
* Based on an analysis using [kolo](https://kolo.app) by @wilhelmklopp and @LilyFoote
* #...
=> feat: Optimize db evaluation

djangocms_versioning/cms_toolbars.py, djangocms_versioning/test_utils/test_helpers.py, tests/test_toolbars.py
`cms_toolbars.VersioningPageToolbar.get_page_content` also retrieved non-page content toolbar objects. Fixes #425
* #425 
* #...
=> fix: get_page_content retrieved non page-content objects from the toolbar

.github/workflows/test.yml, CHANGELOG.rst, djangocms_versioning/admin.py, djangocms_versioning/templates/admin/djangocms_versioning/page/change_form.html, djangocms_versioning/test_utils/factories.py, tests/requirements/dj32_cms41.txt, tests/requirements/dj42_cms41.txt, tests/requirements/dj50_cms41.txt, tests/requirements/dj51_cms41.txt, tests/test_cms_config.py, tests/test_integration_with_core.py
Fixes #428 by adding the optional parameter `exlude_parameters` to the `VersionedChangeList.get_queryset` method. IF provided it will be passed to the `super().get_queryset` method, if not, it will be omitted (to work with Django 4.2).
* #428 
* #...
=> feat: add support for Django 5.0 and 5.1

.github/workflows/test.yml, djangocms_versioning/admin.py, djangocms_versioning/conf.py, djangocms_versioning/forms.py, djangocms_versioning/templates/djangocms_versioning/admin/grouper_form.html, docs/api/advanced_configuration.rst, docs/settings.rst
1. This PR adds **autocomplete** fields and some minimal styling to the grouper form when accessing the version change list:
Before this was a classical select drop-down which quickly gets difficult to handle with a growing number of pages or other grouper objects.
2. Option for less verbose UI: Setting `DJANGOCMS_VERSIONING_VERBOSE_UI ? False` will remove the version change lists from the admin index view (to not clutter it). Version management is still accessible through the versioned models' admins. Also, it will make the version change list less wide by removing the created by date for easier access to the action buttons:
* https://github.com/django-cms/django-cms/pull/8067 required for this PR to work
* #...
[Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is …
=> feat: Autocomplete fields for grouper selection and option for less verbose UI

djangocms_versioning/static/djangocms_versioning/js/indicators.js
Bug Fixes:
- Fixed an issue where the CSRF token was not being fetched correctly.
Fixes #437 
* #437 
* #...
=> fix: Take csrf token from CMS config if possible

.github/workflows/test.yml, djangocms_versioning/cms_toolbars.py
=> fix: For headless mode, django CMS 5.0 adds preview buttons to all views. Do not add again.
