django-cms/djangocms-versioning

tests/test_cms_config.py

Adjusted tests for code added in #28

Adjust tests for is_content_model_versioned

---

djangocms_versioning/cms_toolbars.py
djangocms_versioning/static/djangocms_versioning/js/actions.js

Same post requests as in the admin.
If we need to do something custom for toolbar I'll do it later, for now this should be ok.

Use same js for toolbar buttons as in the admin

---

djangocms_versioning/admin.py
tests/test_admin.py

Blocked by divio/django-cms#6516

Add ?persist=0 to compare requests

---

djangocms_versioning/admin.py
djangocms_versioning/templates/djangocms_versioning/admin/archive_confirmation.html
djangocms_versioning/templates/djangocms_versioning/admin/revert_confirmation.html
djangocms_versioning/templates/djangocms_versioning/admin/unpublish_confirmation.html

Added version number in revert, unpublish and archive's action confir… 

---

djangocms_versioning/constants.py
djangocms_versioning/models.py
djangocms_versioning/operations.py
djangocms_versioning/signals.py
docs/signals.md
tests/test_signals.py

Make versioning emit signals for publish, unpublish and archive.

Versioning publishing signals

---

.circleci/config.yml

Disable caching layer for circleci to kickoff building

---

djangocms_versioning/admin.py
djangocms_versioning/helpers.py
djangocms_versioning/models.py
tests/test_admin.py
tests/test_models.py

When you delete the last version that exist in a grouper it will delete the grouper itself.

Deleting the last version that exist in a grouper deletes the grouper as well

---

djangocms_versioning/monkeypatch/__init__.py
djangocms_versioning/monkeypatch/extensions.py
djangocms_versioning/test_utils/extensions/models.py
djangocms_versioning/test_utils/factories.py
test_settings.py
tests/test_monkeypatch.py

This allows you to be able to copy the page with pagecontent.

Be able fetch a page in extensions even if it is draft

---

djangocms_versioning/models.py

We recently modified the delete method in this PR (https://github.com/divio/djangocms-versioning/pull/202) in that PR I made the somewhat unfortunate decision to assume the field name of the grouper. (This works fine as long as you don't explicitly name the grouper field name). 
This PR amends that mistake.

Don't assume the grouper name, check the actual field name

---

CHANGELOG.rst
djangocms_versioning/__init__.py

* feat: Open compare view in new tab
* Hiding the back button in compare view

Release 1.0.1

---

CHANGELOG.rst
djangocms_versioning/__init__.py

Enable django messages to be hidden after set timeout

Release 1.0.3

---

CHANGELOG.rst
djangocms_versioning/__init__.py

* feat: Added a burger menu in the actions column of the ExtendedVersionAdminMixin.

Release 1.0.4

---

CHANGELOG.rst
djangocms_versioning/static/djangocms_versioning/js/actions.js

Includes some auto formatting that I have inherited probably from Pycharm.

fix: Sideframe always closing when it has been specified to stay open

---

CHANGELOG.rst
djangocms_versioning/__init__.py

* fix: Sideframe always closing when it has been specified to stay open

Release 1.0.5

---

CHANGELOG.rst
djangocms_versioning/__init__.py

* feat: Added injection point for field modification in the ExtendedAdminMixin

Release 1.1.0

---

CHANGELOG.rst
djangocms_versioning/__init__.py

* feat: Add View Published button for page edit or preview mode

Release 1.2.0

---

CHANGELOG.rst
djangocms_versioning/__init__.py

* Release covering the fix to author ordering when using the ExtendedAdminVersionMixin

Release 1.2.1

---

CHANGELOG.rst
djangocms_versioning/__init__.py

* fix: Admin burger menu excluding Preview and Edit buttons in all languages

Release 1.2.2

---

djangocms_versioning/monkeypatch/templatetags.py
djangocms_versioning/test_utils/extensions/models.py
tests/test_monkeypatch.py

The compatibility changes in #291 missed a bit. 🤦 
* #291

fix: Additional change missed in #291

---

djangocms_versioning/admin.py
djangocms_versioning/cms_config.py
djangocms_versioning/cms_toolbars.py
djangocms_versioning/helpers.py
djangocms_versioning/indicators.py
tests/test_extensions.py

Since django CMS 4.1.0rc1 the page tree shows error messages returned by ajax post requests such as toggling navigation status of a page content object. 
No additional message needs not to be sent to the front end. It only results in the error message shown again after a reload.
To avoid accidental creation of many draft objects by clicking the Edit button in the toolbar this PR renames the Edit button to "New Draft" if by clicking it a new draft will be created.
This replaces v3's "Revert to published" function by calling the discard view (without the need of going through "Manage versions")
* `cms-icon-copy`-> `cms-icon-manage-version`
* `cms-icon-layers` -> `cms-icon-compare`
* Use newly provided `cms.icons.css` resource
* https://github.com/fsbraun/django-cms/blob/1b79a030dbc9b09543d0e …

fix: Minor usability improvements

---

.github/workflows/lint.yml

This improves the efficiency of the ruff workflow

ci: Improve efficiency of ruff workflow

---

djangocms_versioning/admin.py
djangocms_versioning/cms_toolbars.py
djangocms_versioning/static/djangocms_versioning/css/versioning.css
djangocms_versioning/static/djangocms_versioning/js/admin/versioning-actions.js
djangocms_versioning/templates/djangocms_versioning/admin/archive_confirmation.html
djangocms_versioning/templates/djangocms_versioning/admin/revert_confirmation.html
djangocms_versioning/templates/djangocms_versioning/admin/unpublish_confirmation.html

fix: Several fixes for the versioning forms: #382, #383, #384

---

CHANGELOG.rst
djangocms_versioning/__init__.py
test_settings.py
tests/requirements/requirements_base.txt

Release 1.3.0
